### PR TITLE
CUST-10118 fixing up docs

### PR DESCRIPTION
**Pull request by JoelRizner**
https://jira.rax.io/browse/CUST-10118

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-65d862a5c8/docs/customer-service/). :bow:

**Comment by JoelRizner** [comment]
thanks @cyrichardson , it's gonna have 3 reviews from the team then we'll merge :slightly_smiling_face:

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-d35a08a01d/docs/customer-service/v1/)

**Comment by soorineeda** [comment]
@JoelRizner can you add Contact in the concepts section.

**Comment by soorineeda** [comment]
@JoelRizner and also update, delete contact needs to be added.

**Comment by JoelRizner** [comment]
prathibha requested to only have read operations

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-6173da1cdb/docs/customer-service/v1/)

**Pull request merged**
